/**
 * This file is autogenerated by helper.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/helper/contract";

const deployedContracts = {
  11155111: {
    FHEIPFSStorage: {
      address: "0x896a6d6Bd3781E2C36Fe1a46c1d83A05f8EB0F2F",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "string",
              name: "cid",
              type: "string",
            },
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "grantee",
              type: "address",
            },
          ],
          name: "AccessGranted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "string",
              name: "cid",
              type: "string",
            },
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "revokee",
              type: "address",
            },
          ],
          name: "AccessRevoked",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "string",
              name: "cid",
              type: "string",
            },
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "FileStored",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_cid",
              type: "string",
            },
          ],
          name: "fileExists",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getAllProviders",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_cid",
              type: "string",
            },
          ],
          name: "getEncryptedKey",
          outputs: [
            {
              internalType: "euint128",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_cid",
              type: "string",
            },
          ],
          name: "getEncryptedPrice",
          outputs: [
            {
              internalType: "euint128",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_cid",
              type: "string",
            },
          ],
          name: "getFileMetadata",
          outputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          name: "getOwnerFiles",
          outputs: [
            {
              internalType: "string[]",
              name: "",
              type: "string[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getProviderCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getProviderStats",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "providerAddress",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "fileCount",
                  type: "uint256",
                },
                {
                  internalType: "euint128",
                  name: "totalPrice",
                  type: "bytes32",
                },
              ],
              internalType: "struct FHEIPFSStorage.ProviderStats[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_provider",
              type: "address",
            },
          ],
          name: "getProviderStatsByAddress",
          outputs: [
            {
              internalType: "uint256",
              name: "fileCount",
              type: "uint256",
            },
            {
              internalType: "string[]",
              name: "cids",
              type: "string[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_cid",
              type: "string",
            },
            {
              internalType: "address",
              name: "_grantee",
              type: "address",
            },
          ],
          name: "grantAccess",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "protocolId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_cid",
              type: "string",
            },
            {
              internalType: "address",
              name: "_revokee",
              type: "address",
            },
          ],
          name: "revokeAccess",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_cid",
              type: "string",
            },
            {
              internalType: "externalEuint128",
              name: "_encryptedKey",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "_inputProof",
              type: "bytes",
            },
            {
              internalType: "externalEuint128",
              name: "_encryptedPrice",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "_priceInputProof",
              type: "bytes",
            },
          ],
          name: "storeFile",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 9441291,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
